// GENERATED by scripts/generate-types.mjs from the public machine contracts.
// Do not edit this file directly.

export type Aip1ExtensionConstant = "VERSION" | "ROLE" | "TENANT_ID" | "CAPABILITIES" | "ANCHOR_CHAIN" | "AUDIENCE" | "ENVIRONMENT";
export type Aip1ExtensionDataType = "INTEGER" | "UTF8String" | "IA5String";
export type Aip1ConformanceLevel = 1 | 2 | 3;

export interface Aip1ExtensionValueByConstant {
  readonly VERSION: 1;
  readonly ROLE: string;
  readonly TENANT_ID: string;
  readonly CAPABILITIES: ReadonlyArray<string>;
  readonly ANCHOR_CHAIN: string;
  readonly AUDIENCE: string;
  readonly ENVIRONMENT: string;
}

export interface Aip1Extension<C extends Aip1ExtensionConstant = Aip1ExtensionConstant> {
  readonly constant: C;
  readonly suffix: number;
  readonly name: string;
  readonly dataType: Aip1ExtensionDataType;
  readonly example: string;
  readonly valueSchema: Readonly<Record<string, unknown>>;
  readonly description: string;
}

export interface Aip1Contract {
  readonly id: "AIP-1";
  readonly oidBase: string;
  readonly certificateLifetime: {
    readonly maximumMinutes: number;
    readonly recommendedMinutes: number;
    readonly issuerBackdateMinutes: { readonly minimum: number; readonly maximum: number };
    readonly verifierGraceSeconds: number;
    readonly maximumClockDriftSeconds: number;
  };
  readonly extensions: ReadonlyArray<Aip1Extension>;
  readonly conformance: {
    readonly levels: ReadonlyArray<{
      readonly level: Aip1ConformanceLevel;
      readonly name: string;
      readonly enforceMaximumLifetime: boolean;
      readonly enforceMaximumClockDrift: boolean;
      readonly requiredExtensions: ReadonlyArray<Aip1ExtensionConstant>;
      readonly conditionalExtensions: ReadonlyArray<{ readonly constant: Aip1ExtensionConstant; readonly condition: string }>;
      readonly validateExtensions: ReadonlyArray<Aip1ExtensionConstant>;
      readonly additionalRequirements: ReadonlyArray<string>;
    }>;
  };
}

export type Ctx1ReservedPrefix = "agent" | "tenant" | "service_account" | "perm" | "budget" | "env" | "role";

export interface Ctx1Contract {
  readonly id: "CTX-1";
  readonly grammar: {
    readonly separator: string;
    readonly minimumSegments: number;
    readonly segmentCharacters: {
      readonly lowercaseAsciiLetters: boolean;
      readonly digits: boolean;
      readonly symbols: ReadonlyArray<string>;
    };
    readonly recommendedMaximumLength: number;
    readonly namesShouldBeStable: boolean;
    readonly unknownCapabilities: string;
    readonly prefixMayContainSeparator: boolean;
  };
  readonly reservedPrefixes: ReadonlyArray<{
    readonly prefix: Ctx1ReservedPrefix;
    readonly purpose: string;
    readonly examples: ReadonlyArray<string>;
  }>;
  readonly invalidExamples: ReadonlyArray<string>;
}

export type Adp1ActionType = "tool_call" | "message" | "plan_update" | "model_inference" | "other";
export type Adp1ObservationType = "tool_result" | "environment" | "user_input" | "error" | "none";
export type Adp1RunStatus = "succeeded" | "failed" | "cancelled" | "timeout";

export interface Adp1AgentStep {
  readonly "index": number;
  readonly "parent_step_index"?: number | null;
  readonly "timestamp": string;
  readonly "action": { readonly "type": "tool_call" | "message" | "plan_update" | "model_inference" | "other"; readonly "name"?: string; readonly "input"?: Readonly<Record<string, unknown>>; readonly [key: string]: unknown; };
  readonly "observation": { readonly "type": "tool_result" | "environment" | "user_input" | "error" | "none"; readonly "output"?: Readonly<Record<string, unknown>>; readonly "error"?: Readonly<Record<string, unknown>> | null; readonly [key: string]: unknown; };
  readonly "reflection"?: { readonly "thought"?: string; readonly "next_action_hint"?: string; readonly "uncertainty"?: number; readonly [key: string]: unknown; };
  readonly "metadata"?: Readonly<Record<string, unknown>>;
  readonly [key: string]: unknown;
}

export interface Adp1AgentRun {
  readonly "version": "adp-1";
  readonly "run_id": string;
  readonly "tenant_id": string;
  readonly "trace"?: { readonly "trace_id"?: string; readonly "span_id"?: string; readonly "parent_span_id"?: string; readonly [key: string]: unknown; };
  readonly "agent": { readonly "agent_id": string; readonly "agent_version"?: string; readonly "framework"?: string; readonly "framework_run_id"?: string; readonly "aip": { readonly "cert_fingerprint": string; readonly "tenant_id"?: string; readonly "capabilities"?: ReadonlyArray<string>; readonly [key: string]: unknown; }; readonly [key: string]: unknown; };
  readonly "context"?: { readonly "task_description"?: string; readonly "workflow_key"?: string; readonly "user_id"?: string; readonly "session_id"?: string; readonly "labels"?: ReadonlyArray<string>; readonly [key: string]: unknown; };
  readonly "steps": ReadonlyArray<Adp1AgentStep>;
  readonly "final_output"?: { readonly "type"?: string; readonly "content"?: string; readonly "format"?: string; readonly [key: string]: unknown; };
  readonly "status": "succeeded" | "failed" | "cancelled" | "timeout";
  readonly "error"?: Readonly<Record<string, unknown>> | null;
  readonly "cancellation"?: Readonly<Record<string, unknown>> | null;
  readonly "started_at": string;
  readonly "completed_at": string;
  readonly "metadata"?: { readonly "total_tokens"?: number; readonly "total_cost_usd"?: number; readonly "models_used"?: ReadonlyArray<string>; readonly [key: string]: unknown; };
  readonly [key: string]: unknown;
}

export type Pvs1Decision = "allow" | "deny" | "escalate";

export interface Pvs1PolicyVerdict {
  readonly "version": "pvs-1";
  readonly "decision": "allow" | "deny" | "escalate";
  readonly "approved": boolean;
  readonly "reasoning": string;
  readonly "policy_violations": ReadonlyArray<string>;
  readonly "confidence_score": number;
  readonly "policy_set"?: ReadonlyArray<string>;
  readonly "metadata"?: { readonly "engine"?: string; readonly "engine_version"?: string; readonly "latency_ms"?: number; readonly "tenant_id"?: string; readonly "agent_id"?: string; readonly [key: string]: unknown; };
  readonly [key: string]: unknown;
}
